- ignore: {name: "Unused LANGUAGE pragma", within: Network.IPLD.Hedgehog}
- ignore: {name: "Redundant bracket", within: Network.IPLD.Hedgehog}
- ignore: {name: "Reduce duplication", within: Network.IPLD.Internal}
